### ISSUE TITLE
Video Gen OUtput

### ISSUE THREAD

**Issue by Chewboctopus** [gokayfem/ComfyUI-fal-API#7]
How do I save a video generation?  The output is "string" which I assumed meant that I would get a URL.  I added a "display any" node bit got no output.  The API did charge me, so not sure how to save my output.

**Comment by gokayfem** [comment]
Hello, i recommend using Video Helper Suite nodes for this. It is most common video saving node on ComfyUI. If you go to your account on fal website you can take the video generated from your requests in the model page. It wont dissappear. You can use load video from url node from this nodes and combine video node from VHS nodes. https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
